### ISSUE TITLE
Define agent's actions

### ISSUE THREAD

**Issue by dgcnz** [utecmlgroup/objectness#2]
An action/step consists on:
* X, Y movement (no blur change)
* Z (in-out) movement (blur change)

- [x] Define a Python module for the agent
- [x] Implement action/step

**Comment by csalcedo001** [comment]
I've just added src/env.py with a definition of the environment _ImageClassificationEnv_. It has a method _step_ that receives an action as a tuple _(acceleration, guess)_ where

* _acceleration_ is a torch vector of size 3 for acceleration in axes x, y, and z. The current implementation receive the desired acceleration from the agent as an action, but we could potentially receive the velocity or even exact position in the plane from the agent too. This could be defined by a parameter of any of these setups will be explored in the future.
* _guess_ is a torch vector of size 10, each position representing the probability given by the agent to each class.

Right now _ImageClassificationEnv_ naively returns a tuple _(next\_state, reward, done)_ such that

* _next\_state_ is the image observed by the agent with size _m_ x _m_. Parameter _m_ must be given on the definition of _ImageClassificationEnv_.
* _reward_ is determined by _guess_ in terms of a threshold that indicates whether any of the options is preferred. If the threshold is not surpassed by any of the classes, the reward is 0. If the threshold is met, then the reward is 10 if the selected class is the answer and -10 otherwise. There is no parameter to modify these reward values implemented yet.
* _done_ is True only when all MNIST images have been given to the model. This means an episode ends after the whole set of training images have been given to the model. We could potentially change this behavior by returning _done_=True when the threshold is met, effectively ending an episode when the agent takes a decision over a single image. This could be switched by a parameter if we are willing to explore both setups in the future.

**Comment by csalcedo001** [comment]
Just committed a module for the agent, should be found in the last pull request for _feature/train\_mnist_ branch.
